name: Auto Upgrade Docker image

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    

jobs:
  auto-upgrade:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Check and upgrade
        run: .github/scripts/check_latest_version.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}